#! /usr/bin/env python3

# a silly script to get the Python lib dir for a prefix to work around distutils
# having no uninstall functionality

from sys import argv
from distutils import sysconfig

print(sysconfig.get_python_lib(prefix = argv[1]))
